
POST http://localhost:4444/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin@demo.com",
    "password": "user$$$"
}
###
GET http://localhost:4444/api/v1/items HTTP/1.1
